# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By

from webdriver_manager.chrome import ChromeDriverManager

class TestOtrotest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_otrotest(self):
    self.driver.get("https://github.com/")
    self.driver.set_window_size(1274, 1053)
    self.driver.find_element(By.LINK_TEXT, "Sign in").click()
    self.driver.find_element(By.ID, "login_field").send_keys("Danielf.r97@hotmail.com")
    self.driver.find_element(By.ID, "password").send_keys("PruebaSelenium.")
    self.driver.find_element(By.NAME, "commit").click()
    self.driver.find_element(By.LINK_TEXT, "New").click()
    self.driver.find_element(By.ID, "repository_name").click()
    self.driver.find_element(By.ID, "repository_name").send_keys("Calidad")
    self.driver.find_element(By.ID, "repository_description").click()
    self.driver.find_element(By.ID, "repository_description").send_keys("Descripción")

  
a=TestOtrotest()
a.setup_method(print(''))
a.test_otrotest()